services:
  rai:
    build:
      dockerfile: Dockerfile
      context: .
      secrets:
        - OPENAI_API_KEY
    ports:
      - 8501:8501
    environment:
      - OPENAI_API_KEY
    command: tail -f /dev/null
    # command: ros2 run rai_whoami rai_whoami_node --ros-args -p robot_description_package:="panther_whoami" 

secrets:
  OPENAI_API_KEY:
    environment: OPENAI_API_KEY